// Client
export { CrucibleClient } from './client.js';
export { CrucibleSocket } from './socket.js';
export { CrucibleApiError, CrucibleClientValidationError } from './errors.js';

// Types (client-specific + domain types — all self-contained)
export type {
  CrucibleClientOptions,
  CrucibleSocketOptions,
  HealthResponse,
  SimulationResponse,
  AssessmentResponse,
  BulkActionResponse,
  OkResponse,
  RestartResponse,
  ListExecutionsParams,
  GetReportOptions,
  SimulationTriggerData,
  SimulationLaunchOptions,
  SimulationStartOptions,
  AssessmentTriggerData,
  AssessmentStartOptions,
  WebSocketCommand,
  WebSocketCommandType,
  WebSocketEventMap,
  WebSocketEventName,
  ScenarioExecutionDelta,
  ExecutionStepDelta,
  Scenario,
  ScenarioStep,
  ScenarioHttpStep,
  ScenarioK6Step,
  ScenarioNucleiStep,
  ScenarioRunnerStep,
  Request,
  ExecutionConfig,
  Expect,
  Extract,
  ExtractRule,
  WhenCondition,
  StepExecutionMode,
  K6StepRunner,
  NucleiStepRunner,
  RunnerFindingSeverity,
  ScenarioExecution,
  ExecutionStepResult,
  ExecutionStatus,
  ExecutionMode,
  ExecutionFilters,
  AssertionResult,
  RunnerSummary,
  PausedState,
  getScenarioStepType,
  isScenarioHttpStep,
  isScenarioK6Step,
  isScenarioNucleiStep,
  isScenarioRunnerStep,
} from './types.js';
